webtalk_init -webtalk_dir E:/My Works/MITS/Multilevel Inverter in FPGA/Verilog Codes/Verilog-Basics/sine_generator/sine_generator.sim/sim_1/behav/xsim/xsim.dir/sine_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 19 22:05:05 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d7b6e32c-0f71-4397-9193-54b002eb4ce7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c56a9f47a176478eb9c3a33ae93c6587" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "93" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3492 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6052_KB" -context "xsim\\usage"
webtalk_transmit -clientid 84951060 -regid "" -xml E:/My Works/MITS/Multilevel Inverter in FPGA/Verilog Codes/Verilog-Basics/sine_generator/sine_generator.sim/sim_1/behav/xsim/xsim.dir/sine_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/My Works/MITS/Multilevel Inverter in FPGA/Verilog Codes/Verilog-Basics/sine_generator/sine_generator.sim/sim_1/behav/xsim/xsim.dir/sine_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/My Works/MITS/Multilevel Inverter in FPGA/Verilog Codes/Verilog-Basics/sine_generator/sine_generator.sim/sim_1/behav/xsim/xsim.dir/sine_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
